"""add payment tables

Revision ID: a1cdf020ea51
Revises: b2de4547cb75
Create Date: 2025-12-01 17:54:19.139348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cdf020ea51'
down_revision = 'b2de4547cb75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_client_id', table_name='bookings')
    op.drop_index('ix_bookings_master_id', table_name='bookings')
    op.drop_index('ix_bookings_salon_id', table_name='bookings')
    op.drop_index('ix_bookings_service_id', table_name='bookings')
    op.drop_index('ix_favorites_salon_id', table_name='favorites')
    op.drop_index('ix_favorites_user_id', table_name='favorites')
    op.drop_index('ix_masters_salon_id', table_name='masters')
    op.drop_index('ix_reviews_client_id', table_name='reviews')
    op.drop_index('ix_reviews_salon_id', table_name='reviews')
    op.drop_index('ix_salons_owner_id', table_name='salons')
    op.drop_index('ix_service_masters_master_id', table_name='service_masters')
    op.drop_index('ix_service_masters_service_id', table_name='service_masters')
    op.drop_index('ix_services_salon_id', table_name='services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_services_salon_id', 'services', ['salon_id'], unique=False)
    op.create_index('ix_service_masters_service_id', 'service_masters', ['service_id'], unique=False)
    op.create_index('ix_service_masters_master_id', 'service_masters', ['master_id'], unique=False)
    op.create_index('ix_salons_owner_id', 'salons', ['owner_id'], unique=False)
    op.create_index('ix_reviews_salon_id', 'reviews', ['salon_id'], unique=False)
    op.create_index('ix_reviews_client_id', 'reviews', ['client_id'], unique=False)
    op.create_index('ix_masters_salon_id', 'masters', ['salon_id'], unique=False)
    op.create_index('ix_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index('ix_favorites_salon_id', 'favorites', ['salon_id'], unique=False)
    op.create_index('ix_bookings_service_id', 'bookings', ['service_id'], unique=False)
    op.create_index('ix_bookings_salon_id', 'bookings', ['salon_id'], unique=False)
    op.create_index('ix_bookings_master_id', 'bookings', ['master_id'], unique=False)
    op.create_index('ix_bookings_client_id', 'bookings', ['client_id'], unique=False)
    # ### end Alembic commands ###
