"""add_is_home_service_to_services

Revision ID: b2de4547cb75
Revises: f8a9b0c1d2e3
Create Date: 2025-12-01 11:25:05.241494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2de4547cb75'
down_revision = 'f8a9b0c1d2e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_home_service column to services table
    op.add_column('services', sa.Column('is_home_service', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove is_home_service column from services table
    op.drop_column('services', 'is_home_service')
    # ### end Alembic commands ###
