#!/bin/bash

# Auditd Setup Script
# Configures audit logging for security monitoring

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "=== Auditd Setup for AURELLE ==="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}✗${NC} This script must be run as root or with sudo"
    exit 1
fi

# Step 1: Install auditd
echo "Step 1: Checking auditd installation..."

if ! command -v auditctl &> /dev/null; then
    echo -e "${YELLOW}⚠${NC}  auditd is not installed"
    echo ""
    read -p "Install auditd now? (Y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo "Installing auditd..."
        apt-get update
        apt-get install -y auditd audispd-plugins

        if [ $? -eq 0 ]; then
            echo -e "${GREEN}✓${NC} auditd installed successfully"
        else
            echo -e "${RED}✗${NC} Failed to install auditd"
            exit 1
        fi
    else
        echo "Please install auditd manually: sudo apt-get install auditd audispd-plugins"
        exit 1
    fi
else
    AUDITD_VERSION=$(auditctl -v 2>&1 | head -1)
    echo -e "${GREEN}✓${NC} auditd is installed: $AUDITD_VERSION"
fi
echo ""

# Step 2: Backup existing configuration
echo "Step 2: Backing up existing configuration..."

BACKUP_DIR="/etc/audit/backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"

if [ -f "/etc/audit/auditd.conf" ]; then
    cp /etc/audit/auditd.conf "$BACKUP_DIR/"
fi

if [ -f "/etc/audit/rules.d/audit.rules" ]; then
    cp /etc/audit/rules.d/audit.rules "$BACKUP_DIR/"
fi

if [ -d "/etc/audit/rules.d/" ]; then
    cp -r /etc/audit/rules.d/* "$BACKUP_DIR/" 2>/dev/null
fi

echo "Backup created: $BACKUP_DIR"
echo ""

# Step 3: Configure auditd
echo "Step 3: Configuring auditd..."

cat > /etc/audit/auditd.conf << EOF
# AURELLE Auditd Configuration
# Generated: $(date)

# Log file settings
log_file = /var/log/audit/audit.log
log_format = ENRICHED
log_group = adm
priority_boost = 4
flush = INCREMENTAL_ASYNC
freq = 50
num_logs = 5
max_log_file = 100
max_log_file_action = ROTATE

# Disk space settings
space_left = 75
space_left_action = SYSLOG
admin_space_left = 50
admin_space_left_action = SUSPEND
disk_full_action = SUSPEND
disk_error_action = SUSPEND

# Network settings (optional)
# tcp_listen_port = 60
# tcp_listen_queue = 5
# tcp_max_per_addr = 1

# Distribution settings
distribute_network = no
EOF

echo -e "${GREEN}✓${NC} auditd.conf configured"
echo ""

# Step 4: Create audit rules
echo "Step 4: Creating audit rules..."

# Clear existing rules
> /etc/audit/rules.d/audit.rules

# Main audit rules file
cat > /etc/audit/rules.d/aurelle-audit.rules << 'EOF'
# AURELLE Audit Rules
# Generated by setup script

# Remove any existing rules
-D

# Buffer size (increase if kernel audit buffer overflow)
-b 8192

# Failure mode (0=silent 1=printk 2=panic)
-f 1

# ============================================
# Monitor authentication and authorization
# ============================================

# Monitor changes to user and group information
-w /etc/group -p wa -k identity
-w /etc/passwd -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity

# Monitor sudo usage
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers.d/ -p wa -k sudoers

# Monitor authentication logs
-w /var/log/auth.log -p wa -k auth_log
-w /var/log/faillog -p wa -k auth_log
-w /var/log/lastlog -p wa -k auth_log

# ============================================
# Monitor system configuration changes
# ============================================

# SSH configuration
-w /etc/ssh/sshd_config -p wa -k sshd_config

# PAM configuration
-w /etc/pam.d/ -p wa -k pam

# Network configuration
-w /etc/network/ -p wa -k network
-w /etc/hosts -p wa -k network
-w /etc/hostname -p wa -k network

# Systemd configuration
-w /etc/systemd/ -p wa -k systemd

# ============================================
# Monitor critical system files
# ============================================

# Kernel modules
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=b64 -S init_module,delete_module -k modules

# System binaries
-w /bin/su -p x -k privileged
-w /usr/bin/sudo -p x -k privileged
-w /usr/bin/ssh -p x -k privileged
-w /usr/bin/scp -p x -k privileged

# ============================================
# Monitor file operations
# ============================================

# Monitor file deletion events
-a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k file_deletion
-a always,exit -F arch=b32 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=4294967295 -k file_deletion

# Monitor file permission changes
-a always,exit -F arch=b64 -S chmod,fchmod,fchmodat -F auid>=1000 -F auid!=4294967295 -k file_permission
-a always,exit -F arch=b32 -S chmod,fchmod,fchmodat -F auid>=1000 -F auid!=4294967295 -k file_permission

# Monitor file ownership changes
-a always,exit -F arch=b64 -S chown,fchown,lchown,fchownat -F auid>=1000 -F auid!=4294967295 -k file_ownership
-a always,exit -F arch=b32 -S chown,fchown,lchown,fchownat -F auid>=1000 -F auid!=4294967295 -k file_ownership

# ============================================
# Monitor application-specific files
# ============================================

# AURELLE application directory
-w /var/www/aurelle/ -p wa -k aurelle_app

# Nginx configuration
-w /etc/nginx/nginx.conf -p wa -k nginx
-w /etc/nginx/sites-available/ -p wa -k nginx
-w /etc/nginx/sites-enabled/ -p wa -k nginx

# PostgreSQL configuration
-w /etc/postgresql/ -p wa -k postgresql

# SSL certificates
-w /etc/letsencrypt/ -p wa -k ssl_certs

# Environment files
-w /var/www/aurelle/.env -p wa -k env_files

# ============================================
# Monitor privileged commands
# ============================================

# Systemctl commands
-w /bin/systemctl -p x -k systemctl

# Service management
-a always,exit -F arch=b64 -S execve -F path=/bin/systemctl -k service_management
-a always,exit -F arch=b32 -S execve -F path=/bin/systemctl -k service_management

# ============================================
# Monitor process execution
# ============================================

# Monitor execution of suspicious commands
-w /usr/bin/wget -p x -k suspicious
-w /usr/bin/curl -p x -k suspicious
-w /usr/bin/nc -p x -k suspicious
-w /usr/bin/ncat -p x -k suspicious

# ============================================
# Monitor security events
# ============================================

# SELinux/AppArmor (if enabled)
-w /etc/apparmor/ -p wa -k apparmor
-w /etc/apparmor.d/ -p wa -k apparmor

# Cron jobs
-w /etc/cron.allow -p wa -k cron
-w /etc/cron.deny -p wa -k cron
-w /etc/cron.d/ -p wa -k cron
-w /etc/cron.daily/ -p wa -k cron
-w /etc/cron.hourly/ -p wa -k cron
-w /etc/cron.monthly/ -p wa -k cron
-w /etc/cron.weekly/ -p wa -k cron
-w /etc/crontab -p wa -k cron
-w /var/spool/cron/ -p wa -k cron

# Firewall configuration
-w /etc/ufw/ -p wa -k firewall
-w /etc/default/ufw -p wa -k firewall

# ============================================
# Make configuration immutable
# ============================================

# Lock audit configuration
-e 2
EOF

echo -e "${GREEN}✓${NC} Audit rules created"
echo ""

# Step 5: Load audit rules
echo "Step 5: Loading audit rules..."

# Stop auditd to load rules
service auditd stop 2>/dev/null

# Load rules
augenrules --load

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓${NC} Audit rules loaded successfully"
else
    echo -e "${RED}✗${NC} Failed to load audit rules"
    echo "Trying alternative method..."
    auditctl -R /etc/audit/rules.d/aurelle-audit.rules
fi
echo ""

# Step 6: Start and enable auditd
echo "Step 6: Starting auditd service..."

systemctl enable auditd
systemctl start auditd

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓${NC} auditd service started successfully"
else
    echo -e "${RED}✗${NC} Failed to start auditd service"
    echo "Check logs: sudo journalctl -u auditd -n 50"
    exit 1
fi

sleep 2
echo ""

# Step 7: Verify audit rules
echo "Step 7: Verifying audit rules..."

RULE_COUNT=$(auditctl -l | grep -v "No rules" | wc -l)

if [ "$RULE_COUNT" -gt 0 ]; then
    echo -e "${GREEN}✓${NC} $RULE_COUNT audit rules loaded"
else
    echo -e "${YELLOW}⚠${NC}  No audit rules loaded"
fi
echo ""

# Step 8: Configure log rotation
echo "Step 8: Configuring log rotation..."

cat > /etc/logrotate.d/audit << EOF
# AURELLE Audit Log Rotation
/var/log/audit/audit.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    postrotate
        /usr/sbin/service auditd restart > /dev/null 2>&1 || true
    endscript
}
EOF

echo -e "${GREEN}✓${NC} Log rotation configured (30 days retention)"
echo ""

# Step 9: Display status
echo "=== Auditd Setup Complete ==="
echo ""
echo -e "${GREEN}✓${NC} Audit logging is now active"
echo ""

echo "Configuration summary:"
echo ""
echo "  Audit Rules: $RULE_COUNT rules loaded"
echo "  Log File: /var/log/audit/audit.log"
echo "  Log Format: ENRICHED"
echo "  Max Log Size: 100MB"
echo "  Log Retention: 5 rotations (30 days)"
echo ""

echo "What is being monitored:"
echo ""
echo "  Authentication & Authorization:"
echo "    ✓ User/group changes (/etc/passwd, /etc/group, etc.)"
echo "    ✓ Sudo usage and sudoers modifications"
echo "    ✓ Authentication logs"
echo ""
echo "  System Configuration:"
echo "    ✓ SSH configuration changes"
echo "    ✓ PAM configuration"
echo "    ✓ Network configuration"
echo "    ✓ Systemd services"
echo ""
echo "  Critical System Files:"
echo "    ✓ Kernel modules (loading/unloading)"
echo "    ✓ System binaries (su, sudo, ssh)"
echo ""
echo "  File Operations:"
echo "    ✓ File deletion/renaming"
echo "    ✓ Permission changes (chmod)"
echo "    ✓ Ownership changes (chown)"
echo ""
echo "  Application Files:"
echo "    ✓ AURELLE application directory"
echo "    ✓ Nginx configuration"
echo "    ✓ PostgreSQL configuration"
echo "    ✓ SSL certificates"
echo "    ✓ Environment files (.env)"
echo ""
echo "  Security Events:"
echo "    ✓ Cron job modifications"
echo "    ✓ Firewall configuration changes"
echo "    ✓ Suspicious command execution (wget, curl, nc)"
echo ""

echo "Useful commands:"
echo ""
echo "  View audit rules:"
echo "    sudo auditctl -l"
echo ""
echo "  Search audit logs by keyword:"
echo "    sudo ausearch -k sshd_config"
echo "    sudo ausearch -k file_deletion"
echo "    sudo ausearch -k aurelle_app"
echo ""
echo "  Search by user:"
echo "    sudo ausearch -ua YOUR_USERNAME"
echo ""
echo "  Search by file:"
echo "    sudo ausearch -f /etc/passwd"
echo ""
echo "  Search for failed events:"
echo "    sudo ausearch --failed"
echo ""
echo "  Generate audit report:"
echo "    sudo aureport"
echo "    sudo aureport --auth"
echo "    sudo aureport --file"
echo "    sudo aureport --failed"
echo ""
echo "  View recent audit events:"
echo "    sudo tail -f /var/log/audit/audit.log"
echo ""
echo "  Search logs in time range:"
echo "    sudo ausearch --start today --end now"
echo "    sudo ausearch --start 08:00 --end 17:00"
echo ""
echo "  Clear audit log (not recommended):"
echo "    sudo sh -c '> /var/log/audit/audit.log'"
echo ""

# Step 10: Example searches
echo "Example audit searches:"
echo ""
echo "  Who modified /etc/passwd?"
echo "    sudo ausearch -f /etc/passwd -i"
echo ""
echo "  What files did user 'john' modify today?"
echo "    sudo ausearch -ua john --start today -i"
echo ""
echo "  Show all sudo usage:"
echo "    sudo ausearch -k privileged -i"
echo ""
echo "  Show failed login attempts:"
echo "    sudo aureport --auth --failed"
echo ""
echo "  Show all file deletions:"
echo "    sudo ausearch -k file_deletion -i"
echo ""

