import { useEffect } from "react";

/**
 * Preload critical routes and resources for better performance
 * This component uses link preload hints to speed up navigation
 */
export function PreloadHints() {
  useEffect(() => {
    // Preload critical route chunks
    const criticalRoutes = [
      "/auth", // Auth page - users often navigate here
      "/salon/", // Salon detail pages - high traffic
      "/profile", // Profile - authenticated users
    ];

    // Create preload links for route chunks
    criticalRoutes.forEach((route) => {
      const link = document.createElement("link");
      link.rel = "prefetch";
      link.as = "script";
      // Note: Actual chunk names will be generated by Vite
      // This is a placeholder for the concept
      document.head.appendChild(link);
    });

    // Preload critical fonts if using custom fonts
    const fontPreload = document.createElement("link");
    fontPreload.rel = "preload";
    fontPreload.as = "font";
    fontPreload.type = "font/woff2";
    fontPreload.crossOrigin = "anonymous";
    // Add font URL when available
    // fontPreload.href = "/fonts/inter.woff2";

    return () => {
      // Cleanup is optional for preload hints
    };
  }, []);

  return null; // This component doesn't render anything
}

/**
 * Prefetch a route's code when user hovers over a link
 * Usage: <PrefetchLink href="/salon/123">View Salon</PrefetchLink>
 */
interface PrefetchLinkProps {
  href: string;
  children: React.ReactNode;
  className?: string;
}

export function PrefetchLink({ href, children, className }: PrefetchLinkProps) {
  const handleMouseEnter = () => {
    // Trigger route prefetch on hover
    // This will be handled by the router's lazy loading
    const link = document.createElement("link");
    link.rel = "prefetch";
    link.href = href;
    document.head.appendChild(link);
  };

  return (
    <a
      href={href}
      className={className}
      onMouseEnter={handleMouseEnter}
      onTouchStart={handleMouseEnter} // For mobile
    >
      {children}
    </a>
  );
}
